FROM rust:1.83.0-slim

COPY . .

RUN apt-get update && apt-get install -y \
    perl \
    perl-modules \
    pkg-config \
    libssl-dev \
    make \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .
