FROM clux/muslrust:stable AS builder

WORKDIR /volume

COPY Cargo.* .
COPY src src

RUN --mount=type=cache,target=/volume/target \
    --mount=type=cache,target=/root/.cargo/registry

RUN cargo build
