name: tests

on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: Create secret
        run: |
          ssh-keygen -t rsa -b 4096 -f /tmp/id_rsa <<< y
          kubectl create ns gitops-operator
          kubectl create secret generic ssh-key -n gitops-operator --from-file=ssh-privatekey=/tmp/id_rsa
          kubectl create ns myns
          kubectl create secret generic ssh-key -n myns --from-file=ssh-privatekey=/tmp/id_rsa

      - name: run tests
        run: cargo test
